services:
  lyclaw-memory:
    image: haikunye/lyclaw-memory:latest
    container_name: lyclaw-memory
    mem_limit: 384m
    ports:
      - "8082:8082"
    environment:
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: 47.104.212.121:8848
      SPRING_CLOUD_NACOS_DISCOVERY_IP: 81.71.120.92
    env_file:
      - .env
    restart: unless-stopped

  lyclaw-reflect:
    image: haikunye/lyclaw-reflect:latest
    container_name: lyclaw-reflect
    mem_limit: 384m
    ports:
      - "8085:8085"
    environment:
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: 47.104.212.121:8848
      SPRING_CLOUD_NACOS_DISCOVERY_IP: 81.71.120.92
    env_file:
      - .env
    restart: unless-stopped
