services:
  lyclaw-action:
    image: haikunye/lyclaw-action:latest
    container_name: lyclaw-action
    mem_limit: 256m
    ports:
      - "8084:8084"
    environment:
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: 47.104.212.121:8848
    env_file:
      - .env
    restart: unless-stopped

  lyclaw-plan:
    image: haikunye/lyclaw-plan:latest
    container_name: lyclaw-plan
    mem_limit: 256m
    ports:
      - "8083:8083"
    environment:
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: 47.104.212.121:8848
    env_file:
      - .env
    restart: unless-stopped
