spring:
  application:
    name: lyclaw-action-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: lyclaw
        group: DEFAULT_GROUP
server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always
lyclaw:
  tool:
    tavily:
      api-key: ${TAVILY_API_KEY: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}   # 空默认值，没设也不报错