spring:
  application:
    name: lyclaw-protocol-service
server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always
