spring:
  application:
    name: lyclaw-memory-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: lyclaw
        group: DEFAULT_GROUP
server:
  port: 8082
